### PR TITLE
Support for python 3

### PR DESCRIPTION
**Pull request by AetherPrior**
making changes in the print statements and import statement works

### CODE REVIEW

**Comment by PranjalGupta2199** [comment]
This app has **tabula** as it's a dependency which hasn't been ported to python3. So simply modifying the code wouldn't work. Try looking for alternatives to **tabula**.

**Comment by AetherPrior** [comment]
I understand what you're saying, but running the app under python3 seems to
work...
I couldn't replicate any error

**Comment by PranjalGupta2199** [comment]
There was no error because I have already uploaded the database. Remove _courses.db_ and then run the app again.

**Comment by AetherPrior** [comment]
There was no courses.db either
I could make the DB as well

**Comment by AetherPrior** [comment]
After making courses.db I could set a timetable up as well
I had no problems whatsoever

**Comment by PranjalGupta2199** [comment]
I have checked your pull request. It works fine. Squash all your three commits into one and then make a pull request.

**Pull request closed without merging**
